INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('AW', 'USD', 'Europe', 'BBB+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('AF', 'USD', 'Oceania', 'AA+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('AO', 'USD', 'North America', 'AA');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('AI', 'USD', 'Africa', 'BBB+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('AX', 'USD', 'Oceania', 'AAA');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('AL', 'USD', 'South America', 'BB+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('AD', 'USD', 'Asia', 'A');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('AE', 'USD', 'Oceania', 'BBB');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('AR', 'USD', 'Africa', 'BB');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('AM', 'USD', 'South America', 'AA');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('AS', 'USD', 'Asia', 'BBB+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('AQ', 'USD', 'Africa', 'BBB');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('TF', 'USD', 'South America', 'AAA');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('AG', 'USD', 'Asia', 'BB');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('AU', 'USD', 'North America', 'A+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('AT', 'USD', 'Asia', 'AAA');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('AZ', 'USD', 'North America', 'A+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('BI', 'USD', 'Europe', 'AA+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('BE', 'USD', 'North America', 'BB');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('BJ', 'USD', 'Europe', 'AAA');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('BQ', 'USD', 'Africa', 'AA');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('BF', 'USD', 'Africa', 'BBB+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('BD', 'USD', 'Africa', 'AA+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('BG', 'USD', 'South America', 'AAA');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('BH', 'USD', 'South America', 'BBB+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('BS', 'USD', 'South America', 'BBB');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('BA', 'USD', 'North America', 'A+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('BL', 'USD', 'Africa', 'BBB');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('BY', 'USD', 'South America', 'AA+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('BZ', 'USD', 'Africa', 'BB+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('BM', 'USD', 'Asia', 'BB');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('BO', 'USD', 'South America', 'A+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('BR', 'USD', 'Africa', 'BB');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('BB', 'USD', 'Asia', 'BB+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('BN', 'USD', 'Oceania', 'AA+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('BT', 'USD', 'Europe', 'AA+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('BV', 'USD', 'Africa', 'BBB+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('BW', 'USD', 'Europe', 'BB+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('CF', 'USD', 'North America', 'AAA');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('CA', 'USD', 'Africa', 'BB+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('CC', 'USD', 'Africa', 'BBB+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('CH', 'USD', 'North America', 'BBB');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('CL', 'USD', 'Asia', 'AA+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('CN', 'USD', 'Oceania', 'A+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('CI', 'USD', 'Oceania', 'BB');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('CM', 'USD', 'Asia', 'BBB');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('CD', 'USD', 'Europe', 'A+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('CG', 'USD', 'Asia', 'BB');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('CK', 'USD', 'Europe', 'AA');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('CO', 'USD', 'Africa', 'BBB+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('KM', 'USD', 'South America', 'BBB+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('CV', 'USD', 'Asia', 'AA');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('CR', 'USD', 'Africa', 'BBB+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('CU', 'USD', 'Africa', 'AA');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('CW', 'USD', 'Oceania', 'AA+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('CX', 'USD', 'North America', 'AAA');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('KY', 'USD', 'Africa', 'BBB');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('CY', 'USD', 'Asia', 'AA');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('CZ', 'USD', 'Africa', 'BBB');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('DE', 'USD', 'Oceania', 'BBB');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('DJ', 'USD', 'North America', 'BBB');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('DM', 'USD', 'Oceania', 'AAA');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('DK', 'USD', 'Oceania', 'A');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('DO', 'USD', 'Asia', 'A+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('DZ', 'USD', 'Oceania', 'BB');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('EC', 'USD', 'North America', 'BB+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('EG', 'USD', 'Europe', 'BBB+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('ER', 'USD', 'Asia', 'A+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('EH', 'USD', 'Asia', 'BB+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('ES', 'USD', 'North America', 'AA+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('EE', 'USD', 'South America', 'BBB+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('ET', 'USD', 'Asia', 'AA+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('FI', 'USD', 'North America', 'BB');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('FJ', 'USD', 'Europe', 'BBB+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('FK', 'USD', 'South America', 'AA+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('FR', 'USD', 'South America', 'BB+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('FO', 'USD', 'Africa', 'AAA');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('FM', 'USD', 'Oceania', 'A+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('GA', 'USD', 'Africa', 'A+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('GB', 'USD', 'South America', 'AAA');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('GE', 'USD', 'Europe', 'BBB');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('GG', 'USD', 'South America', 'AAA');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('GH', 'USD', 'South America', 'BB+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('GI', 'USD', 'North America', 'AA+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('GN', 'USD', 'Oceania', 'BBB+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('GP', 'USD', 'Oceania', 'A+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('GM', 'USD', 'Asia', 'A');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('GW', 'USD', 'Oceania', 'AA+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('GQ', 'USD', 'South America', 'A+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('GR', 'USD', 'Oceania', 'BB');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('GD', 'USD', 'South America', 'BB');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('GL', 'USD', 'Europe', 'AA+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('GT', 'USD', 'Africa', 'AAA');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('GF', 'USD', 'Africa', 'AAA');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('GU', 'USD', 'Africa', 'AAA');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('GY', 'USD', 'South America', 'BBB+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('HK', 'USD', 'Africa', 'AA');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('HM', 'USD', 'Oceania', 'BBB+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('HN', 'USD', 'South America', 'BBB');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('HR', 'USD', 'Europe', 'BBB');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('HT', 'USD', 'Europe', 'AA+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('HU', 'USD', 'Asia', 'A+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('ID', 'USD', 'Asia', 'BB+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('IM', 'USD', 'Asia', 'AA+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('IN', 'USD', 'North America', 'AA');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('IO', 'USD', 'North America', 'A+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('IE', 'USD', 'Asia', 'BBB+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('IR', 'USD', 'Europe', 'BBB');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('IQ', 'USD', 'South America', 'AAA');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('IS', 'USD', 'Europe', 'BB+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('IL', 'USD', 'Europe', 'AA+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('IT', 'USD', 'Asia', 'BB+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('JM', 'USD', 'Africa', 'A+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('JE', 'USD', 'Oceania', 'BBB');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('JO', 'USD', 'Europe', 'A+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('JP', 'USD', 'South America', 'BB+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('KZ', 'USD', 'South America', 'A+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('KE', 'USD', 'Asia', 'AA');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('KG', 'USD', 'Europe', 'BB+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('KH', 'USD', 'North America', 'A');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('KI', 'USD', 'South America', 'A+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('KN', 'USD', 'Oceania', 'AA');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('KR', 'USD', 'Asia', 'A');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('KW', 'USD', 'South America', 'A+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('LA', 'USD', 'Europe', 'BBB+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('LB', 'USD', 'South America', 'A');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('LR', 'USD', 'Africa', 'BB');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('LY', 'USD', 'Oceania', 'BB+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('LC', 'USD', 'Oceania', 'BB');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('LI', 'USD', 'Asia', 'AA');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('LK', 'USD', 'Oceania', 'BBB');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('LS', 'USD', 'South America', 'AA+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('LT', 'USD', 'Asia', 'BB');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('LU', 'USD', 'Europe', 'AA+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('LV', 'USD', 'Africa', 'A');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('MO', 'USD', 'Asia', 'AAA');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('MF', 'USD', 'Asia', 'A');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('MA', 'USD', 'Africa', 'BB');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('MC', 'USD', 'Europe', 'BBB');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('MD', 'USD', 'Europe', 'AAA');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('MG', 'USD', 'South America', 'BB');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('MV', 'USD', 'Oceania', 'BBB+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('MX', 'USD', 'North America', 'AA+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('MH', 'USD', 'Asia', 'BBB+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('MK', 'USD', 'Asia', 'AA');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('ML', 'USD', 'Asia', 'A');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('MT', 'USD', 'South America', 'AAA');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('MM', 'USD', 'Oceania', 'BB');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('ME', 'USD', 'Europe', 'A');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('MN', 'USD', 'Oceania', 'AAA');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('MP', 'USD', 'North America', 'AA+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('MZ', 'USD', 'North America', 'BBB');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('MR', 'USD', 'Asia', 'BB');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('MS', 'USD', 'Oceania', 'A+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('MQ', 'USD', 'Oceania', 'A+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('MU', 'USD', 'South America', 'A');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('MW', 'USD', 'Europe', 'BB+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('MY', 'USD', 'Asia', 'BB');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('YT', 'USD', 'Europe', 'A');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('NA', 'USD', 'South America', 'AA+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('NC', 'USD', 'Africa', 'AA+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('NE', 'USD', 'Europe', 'BBB');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('NF', 'USD', 'Oceania', 'AA+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('NG', 'USD', 'Africa', 'BB+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('NI', 'USD', 'Europe', 'AA+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('NU', 'USD', 'Asia', 'BBB');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('NL', 'USD', 'Africa', 'AA');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('NO', 'USD', 'Oceania', 'BB+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('NP', 'USD', 'South America', 'A+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('NR', 'USD', 'Europe', 'AAA');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('NZ', 'USD', 'South America', 'BBB+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('OM', 'USD', 'Oceania', 'BBB+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('PK', 'USD', 'Africa', 'AA');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('PA', 'USD', 'Oceania', 'A+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('PN', 'USD', 'Europe', 'BB+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('PE', 'USD', 'North America', 'BB');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('PH', 'USD', 'South America', 'BB+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('PW', 'USD', 'Europe', 'AA');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('PG', 'USD', 'Oceania', 'BB+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('PL', 'USD', 'Asia', 'AA+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('PR', 'USD', 'North America', 'A');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('KP', 'USD', 'Europe', 'AA+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('PT', 'USD', 'Europe', 'A+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('PY', 'USD', 'South America', 'BB');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('PS', 'USD', 'Europe', 'AA');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('PF', 'USD', 'Africa', 'AA');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('QA', 'USD', 'Africa', 'BB');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('RE', 'USD', 'Africa', 'BB+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('RO', 'USD', 'Asia', 'BB');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('RU', 'USD', 'Africa', 'BBB+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('RW', 'USD', 'Asia', 'BBB+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('SA', 'USD', 'Africa', 'BB+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('SD', 'USD', 'Africa', 'BB+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('SN', 'USD', 'Europe', 'BBB+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('SG', 'USD', 'Oceania', 'BB+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('GS', 'USD', 'North America', 'BB+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('SH', 'USD', 'Africa', 'AAA');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('SJ', 'USD', 'Europe', 'BBB+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('SB', 'USD', 'Asia', 'AA+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('SL', 'USD', 'North America', 'A');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('SV', 'USD', 'Europe', 'BBB');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('SM', 'USD', 'North America', 'AA+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('SO', 'USD', 'Europe', 'AA');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('PM', 'USD', 'Asia', 'BBB+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('RS', 'USD', 'South America', 'A+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('SS', 'USD', 'Oceania', 'A');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('ST', 'USD', 'South America', 'BB+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('SR', 'USD', 'Africa', 'A+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('SK', 'USD', 'Oceania', 'AA+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('SI', 'USD', 'North America', 'AAA');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('SE', 'USD', 'North America', 'BB');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('SZ', 'USD', 'Asia', 'BB+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('SX', 'USD', 'Africa', 'BB');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('SC', 'USD', 'Africa', 'AA');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('SY', 'USD', 'North America', 'BB');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('TC', 'USD', 'North America', 'BBB+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('TD', 'USD', 'Europe', 'BB+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('TG', 'USD', 'North America', 'AA');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('TH', 'USD', 'Europe', 'A+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('TJ', 'USD', 'South America', 'A');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('TK', 'USD', 'Oceania', 'BB+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('TM', 'USD', 'Europe', 'BBB');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('TL', 'USD', 'North America', 'BBB+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('TO', 'USD', 'Oceania', 'BB');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('TT', 'USD', 'Asia', 'BBB+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('TN', 'USD', 'Asia', 'AA+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('TR', 'USD', 'North America', 'A');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('TV', 'USD', 'Asia', 'AA');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('TW', 'USD', 'Asia', 'BB');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('TZ', 'USD', 'Asia', 'AAA');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('UG', 'USD', 'North America', 'AA');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('UA', 'USD', 'North America', 'AA+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('UM', 'USD', 'Africa', 'BB');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('UY', 'USD', 'Africa', 'BB');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('US', 'USD', 'Asia', 'AAA');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('UZ', 'USD', 'South America', 'AA+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('VA', 'USD', 'Africa', 'AA');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('VC', 'USD', 'South America', 'A');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('VE', 'USD', 'Africa', 'AAA');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('VG', 'USD', 'North America', 'A');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('VI', 'USD', 'Europe', 'A+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('VN', 'USD', 'South America', 'BBB');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('VU', 'USD', 'Oceania', 'AA');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('WF', 'USD', 'North America', 'A');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('WS', 'USD', 'Oceania', 'BBB');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('YE', 'USD', 'Europe', 'A+');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('ZA', 'USD', 'Oceania', 'A');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('ZM', 'USD', 'Asia', 'BBB');
INSERT INTO issuer_entity (country, currency, continent, rating) VALUES ('ZW', 'USD', 'Africa', 'A+');
